Change (again) the meaning of the -c (clean) option to cleanup and remove the test directory after successfully running the tests.  Thus, users can expect that the resources used for running the tests will only be temporarily required during the tests.  In addition, add a note about where the test results can be found.

diff --git a/boost-test-suite/files/boost-test-suite b/boost-test-suite/files/boost-test-suite
--- a/boost-test-suite/files/boost-test-suite
+++ b/boost-test-suite/files/boost-test-suite
@@ -180,12 +180,6 @@ if [ $? -ne 0 ]; then
     exit 1
 fi
 
-# clean directory (if necessary)
-if [ $CLEAN -ne 0 ]; then
-    echo "Cleaning $BASEDIR ..."
-    $RM -rf *
-fi
-
 # remove pre-existing patches
 if [ -e patches ]; then
     echo "Removing pre-existing patches ..."
@@ -288,3 +282,23 @@ if [ $DEBUG -ne 0 -o $VERBOSE -ne 0 ]; then
     echo "$TEST_CMD"
 fi
 exec $TEST_CMD
+
+if [ $? -ne 0 ]; then
+    echo "An error occurred while running the tests.  The results in"
+    echo "$BASEDIR will be preserved in case they are helpful for"
+    echo "determining the cause of the error(s)."
+    exit 1
+fi
+
+# clean directory (if necessary)
+if [ $CLEAN -ne 0 ]; then
+    echo "Cleaning $BASEDIR ..."
+    $RM -rf $BASEDIR
+fi
+
+# report location of test results
+echo "Tests completed successfully.  The test results will be available at:"
+echo
+echo "     http:http://www.boost.org/development/tests/trunk/developer/summary.html"
+echo
+echo "under the heading $SYS / $RUNNER"
